theme: jekyll-theme-slate
title: SciTokens
description: Federated Authorization Ecosystem for Distributed Scientific Computing
include: ["osg-connect/.well-known", "osg-connect/.well-known/openid-configuration"]
